# Generated by Django 2.2.9 on 2020-03-04 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('image_url', models.TextField()),
            ],
            options={
                'ordering': ['product_id'],
            },
        ),
        migrations.CreateModel(
            name='ProductPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(null=True)),
                ('curency', models.CharField(max_length=5, null=True)),
                ('price', models.FloatField(null=True)),
                ('product_description', models.TextField(null=True)),
                ('original_site', models.TextField(null=True)),
                ('images_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_scraper.ImageUrl')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('reviewer_name', models.TextField()),
                ('summary', models.TextField(max_length=50)),
                ('review', models.TextField(max_length=300)),
                ('quality', models.IntegerField()),
                ('price', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
            options={
                'ordering': ['product_id'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedCustomResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(null=True)),
                ('chest_size', models.FloatField(null=True)),
                ('waist_size', models.FloatField(null=True)),
                ('sleeve_length', models.FloatField(null=True)),
                ('shoulder_size', models.FloatField(null=True)),
                ('neck_size', models.FloatField(null=True)),
                ('arm_size', models.FloatField(null=True)),
                ('price', models.FloatField(null=True)),
                ('currency', models.CharField(max_length=3, null=True)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('image_url', models.URLField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sizing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, null=True)),
                ('description', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('currency', models.CharField(max_length=3, null=True)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('image_url', models.URLField(max_length=300, null=True)),
                ('product_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_scraper.ProductPage')),
                ('sizing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_scraper.Sizing')),
            ],
        ),
        migrations.AddField(
            model_name='productpage',
            name='reviews_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_scraper.Reviews'),
        ),
    ]
