# Generated by Django 2.2.7 on 2019-11-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedCustomResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(null=True)),
                ('price', models.FloatField(null=True)),
                ('currency', models.CharField(max_length=3, null=True)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('image_url', models.URLField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(null=True)),
                ('sizing', models.CharField(max_length=5, null=True)),
                ('price', models.FloatField(null=True)),
                ('currency', models.CharField(max_length=3, null=True)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('image_url', models.URLField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoredResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(null=True)),
                ('sizing', models.CharField(max_length=5, null=True)),
                ('price', models.FloatField(null=True)),
                ('currency', models.CharField(max_length=3, null=True)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('image_url', models.URLField(max_length=300, null=True)),
            ],
        ),
    ]
