# Generated by Django 2.2.9 on 2020-02-29 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedCustomResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(null=True)),
                ('chest_size', models.FloatField(null=True)),
                ('waist_size', models.FloatField(null=True)),
                ('sleeve_length', models.FloatField(null=True)),
                ('shoulder_size', models.FloatField(null=True)),
                ('neck_size', models.FloatField(null=True)),
                ('arm_size', models.FloatField(null=True)),
                ('price', models.FloatField(null=True)),
                ('currency', models.CharField(max_length=3, null=True)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('image_url', models.URLField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sizing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, null=True)),
                ('description', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(null=True)),
                ('price', models.FloatField(null=True)),
                ('currency', models.CharField(max_length=3, null=True)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('image_url', models.URLField(max_length=300, null=True)),
                ('sizing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_scraper.Sizing')),
            ],
        ),
    ]
