# Generated by Django 2.2.7 on 2019-11-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedcustomresult',
            name='arm_size',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='scrapedcustomresult',
            name='chest_size',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='scrapedcustomresult',
            name='neck_size',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='scrapedcustomresult',
            name='shoulder_size',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='scrapedcustomresult',
            name='sleeve_length',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='scrapedcustomresult',
            name='waist_size',
            field=models.FloatField(null=True),
        ),
    ]
